apiVersion: v1
kind: PersistentVolume
metadata:
  name: osticket-pv-volume
  labels:
    type: local
    app: osticket
spec:
  storageClassName: manual
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/html"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: osticket-pv-claim
  labels:
    app: osticket
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: osticket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osticket
  template:
    metadata:
       labels:
         app: osticket
    spec:
       containers:
        - env:
          - name: MYSQL_DATABASE
            value: osticket
          - name: MYSQL_PREFIX
            value: ost_
          - name: MYSQL_HOST
            value: osticket-mysql
          - name: MYSQL_PASSWORD
            value: secret
          - name: MYSQL_USER
            value: osticket
          image: osticket/osticket:latest
          name: osticket
          ports:
           - containerPort: 80
          volumeMounts:
           - name: osticket-persistent-storage
             mountPath: /var/www/
       volumes:
           - name: osticket-persistent-storage
             persistentVolumeClaim:
               claimName: osticket-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: osticket
  name: osticket
spec:
  type: LoadBalancer
  ports:
    - name: "8080"
      port: 80
      targetPort: 80
  selector:
    app: osticket
